services:
  college-feedback-platform-database:
    container_name: college-feedback-platform-database
    build:
      dockerfile: Dockerfile.database
      context: .
    environment:
      - POSTGRES_PASSWORD=1234567890
      - POSTGRES_USER=postgres
    ports:
      - 25432:5432
